### ISSUE TITLE
Code - PlayGame method

### ISSUE THREAD

**Issue by jwood36** [cattan13/TicTacToe#31]
Based on your current logic design, there is no way the Player can win.

Review your logic paths and implement a way for the Player to win based on similar evaluations to the System.

**Comment by cattan13** [comment]
The system will always play to block a potential winning move. The player can win the game as long as a move is made that allows for two possible placements that would result in a win. Unless I am misunderstanding. Screenshot of my win attached.

![image](https://user-images.githubusercontent.com/125215899/230247554-47026e88-1191-497d-a501-9688760a6a7a.png)
