### ISSUE TITLE
Duplicated Logic

### ISSUE THREAD

**Issue by jwood36** [cattan13/TicTacToe#8]
Consolidate all the calls to "Console.WriteLine" to a single supportable method to perform this action.

**Comment by cattan13** [comment]
> 

Can I see an example of what you want me to do?

**Comment by cattan13** [comment]
I'm unsure if you want me to create classes for the repetitive functions and call them, or something else. Can you give me an example of what you're looking for? Thanks!

**Comment by jwood36** [comment]
Consolidate all the calls to "Console.WriteLine" to a single supportable method to perform this action.

**Comment by cattan13** [comment]
Created method "Print" for displaying all calls to "Console.WriteLine".
